package solution

import "bytes"

// MultiWriter utility used to collect output generated by the test case(s)
type MultiWriter struct {
	bufs []*bytes.Buffer
}

// NewWriter allocates and returns a new writer used to create output
func (w *MultiWriter) NewWriter() *bytes.Buffer {
	buf := &bytes.Buffer{}

	w.bufs = append(w.bufs, buf)

	return buf
}

// GetOutputs returns the output(s) written by any/all of the writers given out so far...
func (w *MultiWriter) GetOutputs() [][]byte {
	outputs := make([][]byte, 0, len(w.bufs))

	for _, buf := range w.bufs {
		outputs = append(outputs, buf.Bytes())
	}

	return outputs
}
