package solution

import "bytes"

// Multi writer utility used to collect output generated by the test case(s)

type MultiWriter struct {
	bufs []*bytes.Buffer
}

func (w *MultiWriter) NewOutput() *bytes.Buffer {
	buf := &bytes.Buffer{}

	w.bufs = append(w.bufs, buf)

	return buf
}

func (w *MultiWriter) GetOutputs() [][]byte {
	outputs := make([][]byte, 0, len(w.bufs))

	for _, buf := range w.bufs {
		outputs = append(outputs, buf.Bytes())
	}

	return outputs
}
