Feature: event stream formatter
  Smoke test of events formatter.
  Comprehensive tests at internal/formatters.

  Scenario: check formatter is available

    Given a feature "test.feature" file:
      """
        Feature: check the formatter is available
          Scenario: trivial scenario
            Given a passing step
      """
    When I run feature suite with formatter "events"
    Then the rendered events will be as follows:
    """
    {"event":"TestRunStarted","version":"0.1.0","timestamp":9999,"suite":"godog"}
    {"event":"TestSource","location":"test.feature:1","source":"  Feature: check the formatter is available\n    Scenario: trivial scenario\n      Given a passing step"}
    {"event":"TestCaseStarted","location":"test.feature:2","timestamp":9999}
    {"event":"StepDefinitionFound","location":"test.feature:3","definition_id":"functional_test.go:<autogenerated> -\u003e <autogenerated>","arguments":[[0,1]]}
    {"event":"TestStepStarted","location":"test.feature:3","timestamp":9999}
    {"event":"TestStepFinished","location":"test.feature:3","timestamp":9999,"status":"passed"}
    {"event":"TestCaseFinished","location":"test.feature:2","timestamp":9999,"status":"passed"}
    {"event":"TestRunFinished","status":"passed","timestamp":9999,"snippets":"","memory":""}
 """
