Feature: Support scenario injection in BeforeStep

  The framework allows a before step to transform the scenario dynamically.
  Modifying step text and tables and doc strings is supported.

  HOWEVER, the the different formatters have different limitations.
  Cucumber support injection in all locations, whereas Pretty does not (not implemented yet).

  Scenario: Support data injection in BeforeStep with various formatters
    Compare the expectations below to see limitations.

    Given a feature "features/inject.feature" file:
    """
        Feature: inject long value

        Scenario: test scenario
          Given I allow variable injection
          When IgnoredStep: Inject step {{PLACEHOLDER1}}
          And IgnoredStep: Inject table
            | injectedCol     | val |
            | {{PLACEHOLDER2}} | 2   |
          And IgnoredStep: Inject doc string:
            \"\"\"
              Injected docstring : {{PLACEHOLDER3}}
            \"\"\"
          Then IgnoredStep: Godog rendering should not break
          And I disable variable injection

        Scenario Outline: test scenario outline
          Given I allow variable injection
          When IgnoredStep: Inject example step <injectedCol>
          And I disable variable injection

            Examples:
              | injectedCol     |
              | {{PLACEHOLDER4}} |
      """

    When I run feature suite with formatter "pretty"
    Then the rendered output will be as follows:
    """
    Feature: inject long value

      Scenario: test scenario                              # features/inject.feature:3
        Given I allow variable injection                   # <autogenerated>:1 -> *godogFeaturesScenarioInner
        When IgnoredStep: Inject step someverylonginjectionsoweacanbesureitsurpasstheinitiallongeststeplenghtanditwillhelptestsmethodsafety # functional_test.go:<autogenerated> -> <autogenerated>
        And IgnoredStep: Inject table                      # functional_test.go:<autogenerated> -> <autogenerated>
          | injectedCol                                                                                           | val |
          | someverylonginjectionsoweacanbesureitsurpasstheinitiallongeststeplenghtanditwillhelptestsmethodsafety | 2   |
        And IgnoredStep: Inject doc string:                # functional_test.go:<autogenerated> -> <autogenerated>
          \"\"\"
            Injected docstring : {{PLACEHOLDER3}}
          \"\"\"
        Then IgnoredStep: Godog rendering should not break # functional_test.go:<autogenerated> -> <autogenerated>
        And I disable variable injection                   # <autogenerated>:1 -> *godogFeaturesScenarioInner

      Scenario Outline: test scenario outline               # features/inject.feature:16
        Given I allow variable injection                    # <autogenerated>:1 -> *godogFeaturesScenarioInner
        When IgnoredStep: Inject example step <injectedCol> # functional_test.go:<autogenerated> -> <autogenerated>
        And I disable variable injection                    # <autogenerated>:1 -> *godogFeaturesScenarioInner

        Examples:
          | injectedCol      |
          | {{PLACEHOLDER4}} |

    2 scenarios (2 passed)
    9 steps (9 passed)
    9.99s

    """

    When I run feature suite with formatter "cucumber"
      # The Cucumber formatter permits injection of docstring and tables
    Then the rendered json will be as follows:
    """
    [
        {
            "uri": "features/inject.feature",
            "id": "inject-long-value",
            "keyword": "Feature",
            "name": "inject long value",
            "description": "",
            "line": 1,
            "elements": [
                {
                    "id": "inject-long-value;test-scenario",
                    "keyword": "Scenario",
                    "name": "test scenario",
                    "description": "",
                    "line": 3,
                    "type": "scenario",
                    "steps": [
                        {
                            "keyword": "Given ",
                            "name": "I allow variable injection",
                            "line": 4,
                            "match": {
                                "location": "\u003cautogenerated\u003e:1"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        },
                        {
                            "keyword": "When ",
                            "name": "IgnoredStep: Inject step someverylonginjectionsoweacanbesureitsurpasstheinitiallongeststeplenghtanditwillhelptestsmethodsafety",
                            "line": 5,
                            "match": {
                                "location": "functional_test.go:632"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        },
                        {
                            "keyword": "And ",
                            "name": "IgnoredStep: Inject table",
                            "line": 6,
                            "match": {
                                "location": "functional_test.go:632"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            },
                            "rows": [
                                {
                                    "cells": [
                                        "injectedCol",
                                        "val"
                                    ]
                                },
                                {
                                    "cells": [
                                        "someverylonginjectionsoweacanbesureitsurpasstheinitiallongeststeplenghtanditwillhelptestsmethodsafety",
                                        "2"
                                    ]
                                }
                            ]
                        },
                        {
                            "keyword": "And ",
                            "name": "IgnoredStep: Inject doc string:",
                            "line": 9,
                            "doc_string": {
                                "value": "  Injected docstring : someverylonginjectionsoweacanbesureitsurpasstheinitiallongeststeplenghtanditwillhelptestsmethodsafety",
                                "content_type": "",
                                "line": 10
                            },
                            "match": {
                                "location": "functional_test.go:632"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        },
                        {
                            "keyword": "Then ",
                            "name": "IgnoredStep: Godog rendering should not break",
                            "line": 13,
                            "match": {
                                "location": "functional_test.go:632"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        },
                        {
                            "keyword": "And ",
                            "name": "I disable variable injection",
                            "line": 14,
                            "match": {
                                "location": "\u003cautogenerated\u003e:1"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        }
                    ]
                },
                {
                    "id": "inject-long-value;test-scenario-outline;;2",
                    "keyword": "Scenario Outline",
                    "name": "test scenario outline",
                    "description": "",
                    "line": 23,
                    "type": "scenario",
                    "steps": [
                        {
                            "keyword": "Given ",
                            "name": "I allow variable injection",
                            "line": 17,
                            "match": {
                                "location": "\u003cautogenerated\u003e:1"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        },
                        {
                            "keyword": "When ",
                            "name": "IgnoredStep: Inject example step someverylonginjectionsoweacanbesureitsurpasstheinitiallongeststeplenghtanditwillhelptestsmethodsafety",
                            "line": 18,
                            "match": {
                                "location": "functional_test.go:632"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        },
                        {
                            "keyword": "And ",
                            "name": "I disable variable injection",
                            "line": 19,
                            "match": {
                                "location": "\u003cautogenerated\u003e:1"
                            },
                            "result": {
                                "status": "passed",
                                "duration": 0
                            }
                        }
                    ]
                }
            ]
        }
    ]

    """
