# This script uploads application binaries as GitHub release assets.
name: release-assets
on:
  release:
    types:
      - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write # Required to upload assets

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: stable
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Build artifacts
        run: |
          make artifacts
      - name: Upload linux amd64 binary
        run: gh release upload "${{ github.event.release.tag_name }}" ./_artifacts/godog-${{ github.event.release.tag_name }}-linux-amd64.tar.gz --clobber
      - name: Upload linux arm64 binary
        run: gh release upload "${{ github.event.release.tag_name }}" ./_artifacts/godog-${{ github.event.release.tag_name }}-linux-arm64.tar.gz --clobber
      - name: Upload darwin amd64 binary
        run: gh release upload "${{ github.event.release.tag_name }}" ./_artifacts/godog-${{ github.event.release.tag_name }}-darwin-amd64.tar.gz --clobber
