name: test
on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - '**'

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        go-version: [ oldstable, stable ] # Lowest supported and current stable versions.
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Go cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache
      - name: Run gofmt
        run: gofmt -d -e . 2>&1 | tee outfile && test -z "$(cat outfile)" && rm outfile
      - name: Run staticcheck
        if: matrix.go-version == 'stable'
        uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ matrix.go }}

      - name: Run go vet
        run: |
          go vet ./...
          cd _examples && go vet ./... && cd ..
      - name: Run go test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
          cd _examples && go test -v -race ./... && cd ..
      - name: Run godog
        run: |
          go install ./cmd/godog
          godog -f progress --strict
      - name: Report on code coverage
        if: matrix.go-version == 'stable'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          file: ./coverage.txt
